### ISSUE TITLE
Will the Anvil work soon?

### ISSUE THREAD

**Issue by LucGamesYT** [GameModsBR/Nukkit#96]
Will the Anvil work soon? I'd really appreciate it! :)

**Comment by joserobjr** [comment]
Yes, the way bedrock handles fake UI inventories is messy, I couldn't make it work on the first try but I'm having new ideas

**Comment by LucGamesYT** [comment]
Ok nice :D

**Comment by joserobjr** [comment]
It's almost fully functional, I'm having only this issue right now: #98
